# docker-compose Nginx
version: '3'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - 80
    expose:
      - 80
    volumes:
      - .:/code
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env
    networks:
      - nginx-proxy
    command: [ 'nginx-debug', '-g', 'daemon off;']
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
