# docker-compose Nginx
version: '2.4'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - 80
    expose:
      - 80
    volumes:
      - .:/code
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-router"

      - "traefik.http.routers.nintendo-e3.rule=Host(`e3.nek.moe`)"
      - "traefik.http.routers.nintendo-e3.entrypoints=websecure"
      - "traefik.http.routers.nintendo-e3.tls.certresolver=certbot"
    networks:
      - web-router
    command: [ 'nginx-debug', '-g', 'daemon off;']
  node:
    image: node
    volumes:
      - .:/code
    build:
      context: .
      dockerfile: Dockerfile
networks:
  web-router:
    external: yes
    name: web-router
